Hue_low : 89 
Hue_high : 128 
Saturation_low : 40 
Saturation_high : 132 
Value_low : 94 
Value_high : 245 
Area_min : 167 
Area_max : 500 
Width_min : 167 
Width_max : 500 
green_filter : True 
camera_start_height : 240 
camera_bottom_height : 840 
camera_left_width : 0 
camera_right_width : 800 
