Hue_low : 0 
Hue_high : 0 
Saturation_low : 0 
Saturation_high : 255 
Value_low : 0 
Value_high : 255 
Area_min : 10 
Area_max : 10 
Width_min : 10 
Width_max : 10 
green_filter : True 
camera_start_height : 300 
camera_bottom_height : 600 
camera_left_width : 0 
camera_right_width : 800 
